on:
  push:
  pull_request:

name: Talk CI
jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: cargo test
        run: cargo test
